# Generated by Django 5.1.5 on 2025-02-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
